version: '3.3'

services:
  grpc-server:
    build: .
    command: /app/grpc-server
    ports:
      - "50051:50051"
    volumes:
      - ./data.json:/app/data.json
    networks:
      - post-network
    environment:
      - DATA_FILE=/app/data.json

  graphql-server:
    build: .
    command: /app/graphql-server
    ports:
      - "8080:8080"
    depends_on:
      - grpc-server
    networks:
      - post-network
    environment:
      - GRPC_SERVER_ADDRESS=grpc-server:50051

networks:
  post-network:
    driver: bridge